### ISSUE TITLE
[Feature Request] Have all NPCS roll and choose highest result as leader

### ISSUE THREAD

**Issue by GhostwheelX** [caewok/fvtt-zipper-initiative#1]
Might is be possible to roll initiative for _all_ of the NPCs, and choose the highest result (rather than highest modifier) as the "leader" for initiative? It's just that as it is, the PCs always have a massive advantage, and this would help balance it out, so having that as an option that could be checked in the settings would help greatly.

**Comment by caewok** [comment]
Added in v0.1.2. Thanks for the idea!
