### ISSUE TITLE
Many deprecation warnings

### ISSUE THREAD

**Issue by noncasus** [caewok/fvtt-zipper-initiative#2]
Hi,

I've noticed that if you open console you'll see many of the same deprecation warning basically mentioning to update line ~319 of combat.js where you have:

`const abilityId = init?.ability || CONFIG.DND5E.initiativeAbility;`

And it should be changed to:

`const abilityId = init?.ability || CONFIG.DND5E.defaultAbilities.initiative;`

Once changed the dep warnings disappear, however it does make me wonder if there is some kind of inefficiency. (I'm basing this on the sheer amount of dep messages)

Using:
Foundry v11
Dnd v3.1.2

**Comment by caewok** [comment]
Thanks for writing this up. Addressed in v0.1.3.
