### ISSUE TITLE
[Feature Request] DSN rolls?

### ISSUE THREAD

**Issue by noncasus** [caewok/fvtt-zipper-initiative#3]
Any chance to update the module so we see DSN rolls for NPCs when we hit "Roll All NPCs"?

Even if they are fake rolls. (I know the initiative is changed by the module, which is great, but it kind of feels good to see all those little dice roll haha)

**Comment by caewok** [comment]
Added in v0.1.3. Thanks for the suggestion! And they are not completely fake—the rolls are used to determine the order.
