### ISSUE TITLE
[Feature Request]Select Next Player

### ISSUE THREAD

**Issue by EpsilonRose** [caewok/fvtt-zipper-initiative#4]
This might be a bit out of scope, but would it be possible to add the ability to see who hasn't gone yet, this round, and then select the next person on your team.

So, for example, at the end of my turn, I pick Blake to go next. Then Baddie A goes and at the end of their turn the select Baddie B, then Blake goes and the cylce repeats until every one has gone once and the round ends.

There are a number of modules for that implement popcorn initiative, which is esentially what I'm talking about, but they don't implement the zipper portion of it, so you're picking from anyone and their's no way to pick an ally who will go after an enemy or to see who's turn is queued up.

**Comment by caewok** [comment]
Added in v0.2.1. Thanks for the idea, it is an intriguing addition!
