### ISSUE TITLE
[Bug] Zipper Initiative leaves additional enemies at the bottom

### ISSUE THREAD

**Issue by GhostwheelX** [caewok/fvtt-zipper-initiative#6]
So while zipper initiative works perfectly most of the time, when there are many enemies then they are all put at the bottom of the initiative after being put one after another.

For example, currently when you have 4 players and 10 enemies, the initiative might look like P1, E1, P2, E2, P3, E3, P4, E4, E5, E6, E7, E8, E9, E10.

However, this goes against the entire point of the zipper initiative system. Would it be possible to make it go down and up the initiative order?

So in an ideal situation, the above initiative order would instead be P1, E1, E8, E9, P2, E2, E7, E10, P3, E3, E6, P4, E4, E5.

I'm not sure if I'm clear, so feel free to ask me on Discord if what I'm asking isn't apparent.

Thank you very much 🙂

**Comment by caewok** [comment]
I think I understand what you mean. I added an "interleave" setting in v0.2.1 that does this. 

It is not a bug to leave all the remaining enemies at the bottom, but rather intended behavior as described by at least some versions of the zipper initiative. But I get why that is not always desirable, thus the new setting!
